name: "Tagged Release"

on:
  push:
    tags:
      - "**"

jobs:
  tagged-release:
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.HUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Release for Modern
        uses: BigWigsMods/packager@v2
        with:
          args: -m .pkgmeta -w 0
